apiVersion: apps/v1
kind: Deployment
metadata:
  name: mail-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mail-service
  template:
    metadata:
      labels:
        app: mail-service
    spec:
      containers:
      - name: mail-service
        image: "ercsnmrs/mail-service:1.0.0"
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
          requests:
            memory: 256Mi
            cpu: "0.2"
        env:
          - name: MAIL_DOMAIN
            value: "logs"
          - name: MAIL_HOST
            value: "admin"
          - name: MAIL_PORT
            value: "1025"
          - name: MAIL_USERNAME
            value: ""
          - name: MAIL_PASSWORD
            value: ""
          - name: MAIL_ENCRYPTION
            value: "none"
          - name: FROM_NAME
            value: "Stephen Sy"
          - name: FROM_ADDRESS
            value: "stephen@sy.com"
        ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: mail-service
spec:
  selector:
    app: mail-service
  ports:
    - protocol: TCP
      name: main-port
      port: 80
      targetPort: 80


